@startuml
actor Player
actor :Another Player:

Player ->       (Begin Game)
                (Begin Game) <- :Another Player:
Player -->      (Movement)
Player --->     (Magic)
                (Magic) <. (Cast Spell)
                (Magic) <. (Counterspell)
Player ---->    (Select Unit)
Player ----->   (View Statistics) 
                (View Statistics) <. (View Character Statistics)
                (View Statistics) <. (View Game Statistics)
Player ------>  (Combat)
Player -------> (Conduct Diplomacy)
                (Conduct Diplomacy) <- :Another Player:

@enduml
