@startuml

title Tyler Jaszkowiak Diplomacy Cases

actor Player


Player ->    (Select Subset of Stack)


Player ->      (Select Ally Candidate)
Player -->     (Create Emissary)
Player -->     (Eliminate Emissary):extends
Player --->    (Move Diplomacy Marker)
Player -->     (Conduct Diplomacy)
Player -->     (Sacrifice Human)
(Sacrifice Human) ..|>  (Select Subset of Stack) :uses
(Conduct Diplomacy) ..|> (Move Diplomacy Marker) :uses
(Sacrifice Human)  ..|> (Move Diplomacy Marker) :uses


@enduml
