@startuml
actor Player

Player --->    (Select Subset of Stack)

Player --->    (View Char/Unit Statistics)
Player --> (Cast Untargeted Spell)
Player --> (Cast Targeted Spell)
(Cast Targeted Spell) --|> (Cast Untargeted Spell) :extends
(Cast Targeted Spell) ..|> (Select Subset of Stack) :uses
Player --> (Cast Conjuring Spell)
(Cast Conjuring Spell) --|> (Cast Untargeted Spell) :extends
Player --> (Manna Transfer)
(Manna Transfer) --|> (Cast Untargeted Spell) :extends

@enduml
